#!/bin/bash

IN="ERR"
PLANE="ERR"
MODE="ERR"
NI="ERR"
NP="ERR"

if [ -f fid ]; then
echo "File exist: fid"
IN=fid
fi

if [ -f procpar ]; then
PLANE=`awk '/^ncyc /{f=1;next}f{print $1;exit}' procpar`
echo "Number of ncyc/planes in procpar: $PLANE"
MODEPAR=`awk '/^array /{f=1;next}f{print $2;exit}' procpar`
IFS=',' read -a MODEARR <<< "$MODEPAR"
#echo ${MODEARR[0]}
#echo ${MODEARR[1]}
if [ ${MODEARR[0]} == '"phase' ]; then
MODE=1
fi
if [ ${MODEARR[0]} == 'phase"' ]; then
MODE=0
fi
echo "Array is recorded: $MODEPAR, so mode should be: $MODE"
NI=`awk '/^ni /{f=1;next}f{print $2;exit}' procpar`
echo "Found in the file procpar that ni=$NI"
NP=`awk '/^np /{f=1;next}f{print $2;exit}' procpar`
echo "Found in the file procpar that np=$NP"
fi

echo 
echo "I suggest following sort_psedo3D command:"
echo "####################"
echo "sort_pseudo3D -in $IN -plane $PLANE -mode $MODE -ni $NI -np $NP"
echo "####################"

echo "After 'sort_pseudo3D' convert one of the spectra normally using 'nmrDraw' (Proc:Convert Varian)."
echo "NOTICE: You will need to change: 'Spectrometer Input' from ./fid to ./0.fid."
echo 
echo "When you have made a 'fid.com', run the next CPMG script"

