#!/bin/tcsh
if ( $1 == ) then
echo "Use together with file/sparky list"
echo "script sparkylists.csv" 
exit
endif
set FILES=`awk '{print $1}' $1`
set SPARKYS=`awk '{print $2}' $1`
set time_T2S=`awk '{print $3}' $1`
set NCYCS=`awk '{print $4}' $1`
set nuS=`awk '{print $5}' $1`
set FILESNR=${#FILES}
set DAT=./dat
set NESSY=./nessy
set NESSYD=nessy_proj
set NESSYP=CPMG.NESSY
rm -rf $DAT
rm -rf $NESSY
rm -rf $NESSYD
mkdir -p $DAT
mkdir -p $NESSY
mkdir -p $NESSYD
set NUARR=""
foreach I (`seq $FILESNR`)
    set FILE=${FILES[$I]}
    set SPARKY=${SPARKYS[$I]}
    set NCYC=${NCYCS[$I]}
    set time_T2=${time_T2S[$I]}
    set nu=${nuS[$I]}
    set NUARR="${NUARR} ${nu}"
    #
    NLS_stPeakList.pl $FILE $SPARKY > peaks${I}.dat
    #echo "NLS_stPeakList.pl $FILE $SPARKY > peaks${I}.dat"
    echo "$FILE">peaks${I}.lst
    seriesTab -in peaks${I}.dat -out peaks${I}.ser -list peaks${I}.lst -sum -dx 1 -dy 1
    #echo "seriesTab -in peaks${I}.dat -out peaks${I}.ser -list peaks${I}.lst -sum -dx 1 -dy 1"
    tail -n +14 peaks${I}.ser | awk '{print $1, $7, $6}' > $NESSY/peaks${I}.nessy
    # To save.nessy
    set RESNS=`tail -n +14 peaks${I}.ser | awk '{print $7}'`
    set PEAKS=`tail -n +14 peaks${I}.ser | awk '{print $1}'`
    mv peaks${I}.dat $DAT; mv peaks${I}.ser $DAT; mv peaks${I}.lst $DAT
end

# Make nessy.save file
# Make residue sequence
echo "Project folder:<>$PWD" > $NESSYP
echo "CPMG delay:<>['$time_T2']" >> $NESSYP
set SEQS="Sequence:<>0<>['', '', "
set SEQE="'']"
set PEAKNR=${#PEAKS}
foreach J (`seq $PEAKNR`)
    set RESN=${RESNS[$J]}
    set PEAK=${PEAKS[$J]}
    set SEQT="'$RESN', "
    set SEQS="${SEQS}${SEQT}"
end
set SEQS="${SEQS}${SEQE}"
echo $SEQS >> $NESSYP
# Make hight data
set i=1
foreach I (`seq $FILESNR`)
    set FILE=${FILES[$I]}
    set SPARKY=${SPARKYS[$I]}
    set NCYC=${NCYCS[$I]}
    set time_T2=${time_T2S[$I]}
    set nu=${nuS[$I]}
    #
    set HIGHTS=`tail -n +14 $DAT/peaks${I}.ser | awk '{print $6}'`
    set CSHS=`tail -n +14 $DAT/peaks${I}.ser | awk '{print $4}'`
    set CSNS=`tail -n +14 $DAT/peaks${I}.ser | awk '{print $5}'`
    set HIGHTNR=${#HIGHTS}
    set DATS="Datasets:<>0<>${i}<>['', '', '"
    set DATE="'']"
    foreach J (`seq $HIGHTNR`)
        set HIGHT=${HIGHTS[$J]}
        set CSH=${CSHS[$J]}
        set CSN=${CSNS[$J]}
        set DATT="'$HIGHT', "
        set DATS="${DATS}${DATT}"
    end
    set DATS="${DATS}${DATE}"
    echo $DATS >> $NESSYP
    @ i++
end
echo "CPMG relaxation delay:<>0<>$time_T2" >> $NESSYP
echo "Experiment:<>0<>cpmg" >> $NESSYP
# Make nu freq
set NUS="CPMG frequencies:<>0<>["
set NUE="'']"
set NUARR=`echo $NUARR`
set NUNR=${#NUARR}
echo $NUNR
echo $NUARR
foreach J (`seq $NUNR`)
    set NU=${NUARR[$J]}
    set NUT="'$NU', "
    set NUS="${NUS}${NUT}"
end
set NUS="${NUS}${NUE}"
echo $NUS >> $NESSYP
mv $NESSYP $NESSYD
echo "Done with making nessy project file. Open nessy project"
echo "cd $NESSYD"
echo "nessy $NESSYP"
